//
//  day12.swift
//  AoC2024
//
//  Created by a on 12/12/2024.
//

class Day12 {
    let input1 = [
        "AAAA",
        "BBCD",
        "BBCC",
        "EEEC",
    ]
    
    let input2 = [
        "RRRRIICCFF",
        "RRRRIICCCF",
        "VVRRRCCFFF",
        "VVRCCCJFFF",
        "VVVVCJJCFE",
        "VVIVCCJJEE",
        "VVIIICJJEE",
        "MIIIIIJJEE",
        "MIIISIJEEE",
        "MMMISSJEEE",
    ]
    
    let input3 = [
        "BBBBBBBBGGGGGGGGGDDDDDDDDDDDDDXXXXXXXXXPPPPPPPPPPADDDDDDPPPDDDNNNNNNIXXXDXLLLLLDDNDDUUUGGGGGGGGGGGGGGGFFFSSMSSIIIIIIIIIIIIQGGGGGDDDDDDDDDDDD",
        "BBBBBBGGGGGGGGGGGGGDDDDDDDDDDXXXXXXXXFXPPPPPPPMPPAADDDDPPPPPNNNNNNNNXXXXXXXLLLLLDDDDUDUGGGGGGGGGGGGGGFFFFFSSSSIIIIIIIIIIIQQGGGGGDDDDDDDDDDDD",
        "BBBBBBBGTGGGGGGGGGGDDDDDDDDDXXXXXXXXXXXPPPPPMMMPAAADPPDPPPPPPPENNNNNXXXXXXXXLLLDDDDDDDGGGGGGGGGGGGGGGGGASSSSSSSIIIIIIIIIIQQGGGGGDDDDDDDDDDDD",
        "BBBBGGGGGGGGGGGGGGGDDDDDDDDDDXXXXXXXXXXXQPPMMMMAAAJPPPPPPPPPEEENNNNNXXXXXXWXXXLDDDDUDDDDGGGGGGGGGGGGGGGSSSSSSSSISIIIIIIQIIQGGGGGDDDDDDDDDDDD",
        "BBBGGGGGGGGGGGGGGGDDDDDDDDDDDDXXXXXXXXXQQQPPMFFFAAJPPPPPPPPEENNNNNNXXXXXXXXXXXDDDDDDDDDDGGGGGGGGGGGGGGSSSSSSSSSSSIIIIIQQQQQQQGQGGDDDKDDDDDDD",
        "BBBBGGGGGGGGGGGGGGDDDDDDDDDDXXXXXXXXXXXXWQQQMFFAAAAPPPPPPPPNNNNNNNXXXXXXXXXXXDDDDDDDDSSDSSGGGGGGGGGGGYSSSSSSSSSSSIIIIIIQQQQQQQQGGGHHKDDDDDDD",
        "BBBBGGGGGGGGGGGGGDDDDDDDDDDDDXXXXXXXXYYXWQQQQFFAAAAAKPPPPPPPPNNNNNXXXXXXXXXXXDDDDDDDDSSSSSSSSGSSGGGGGGSSSSSSSSSSSIIIIIIQQQQQQQGGGHHHHMDDDDDD",
        "DDBBGFGGGGGGAAAAGQDDDDDDDDDDDDXXXXXXQYYYQQQQQQQNAAPPPPPPPPPPNNNNNNXXXXXXXXXXXDDTTTTTTTTTTTSSSGSSSSSGGGSSSSSSSSSSIIIIIIQQQQQQQQQGGHHHHHHHDFDF",
        "DBBBAAGGGGLGDDDDDDDDDDDDDDDDDXXXXXXXQYQQQQQQQQQNABPPPPPPPPPPPNNNNNXNXXXXXXXXBDDTTTTTTTTTTTSSSSSSSSSGSSSSSSSSSSSIIIIIIQQQQQQQQQQHGHHHHHFFFFFF",
        "DAAAADDGEEEEEEEEDDDDDDADDDDDDXXXXXXTQQQQQQQQQQNNNBBBPPPPPPPPNNNNNNNNNXXXXXXXXXXTTTTTTTTTTTTTSTTTTWSSSSSSSSSSSSSIIIIQQQQQQQQQQQQHHHHHHHHFFFFF",
        "DAAAADDDEEEEEEEEEEEEEDDTLDDDDEXXXTTTQQQQQQQQQQQQQBBBBJPPPPNNNNNNNNNNXXXXXXXXTTQTTTTTTTTTTTTTTTTTTTWSSSSSSSSSSASQQQQQQQQQQQQQQQHHHHHHHHHFBFFF",
        "DDDDDDDEEJEEEEEEEEEEEEDDLLLDDTDXXXTTTQQQQQQQQQQQBBBBBPPPPXNNNNNNNNNNNXXXXXXXTTQQQQQQQBBTTTTTTTTTTTWDSSSHHHHHHASGZPQQQQQQQQQQQQQQHWHHHHBBBBFF",
        "DDDDDDDDDWWEEEEEEEEEEEDLLLLCCTTTTTTTTTQQQQQQQQQQQBBBBBPPPXNNNNNNNNNNNXXXXXXDQQQQQQQQQBBTTTTTTTTTTTDDDHHHHHHHHAHZZPPQZQQQQQQQQQQQQQDDHHBBBBBB",
        "DDDDDDDDWTWWWWWEEEEEEELLLLCCCTTTTTTTTTTQQQQQQQQQQBBBBBBBPXNNNNNNNNNNXXXXXXXXXDQQQQQQQQQTTTTTTTTTTTDDDMHDHHHHHHHZZZZZZQQQQQQQQQQQQQDHHBBBBBBB",
        "DDDDDDDWWWUWWWWEEEEEEELLLLLCCCCTTTTTTTTTTQQQQQQQBBBBBBBBXXFENNNNNNNNXXXXXXXXCQQQQQQQQQQQEQWTTTTTTTDDDDDDDHHHHHCZZZZZZZQQQQQQQQQQQQDHRBBBBBBB",
        "DDDDDDDWWWWWWWWWNEEEEELLLLTTTTTTTTTTTTTTTQQQQQBBBBBBBBBXXFFFFFFFNNRNXXXXXXXXQQQQQQQQZQQQQQWTTTTTTTDDDDDDDHHHHHHZZZZZZZQQQQQQQQIQLQVMVABBBBBB",
        "DDDDDDWWWWWWWWWWNNEEEEEEELLTTTTTTTTTTTTTTTTTTQBBBBBBBBXXXFFFFFFFFHFKFXXXXXSSSSSQQPPQQQQQWWWTTTTTTTDDDDDDDHHHHHHZZZZZZZZQZZZQQQQLLLVVVVVBBBBB",
        "DDDDDDDWWWWWWWWWWNNNGEZZZTTTTTTTTTTTTTTTTTTTTBBBBBBBBBXXXFFFFFFFFFFFFKXKXXSSSSSSSSPPPPQQWWWWWTTTTDDDDDDDHHHHHHHZZZZZZZZZZZQQQQLLLLLVVVVVBBBB",
        "DDDDDDIWWWWWWWWWWNNNNNNZNSSGXTTTTTTTTTTTTTTTTBBBIIBBBBXXXFFFFFFFFFFFKKKKXJVJSSSSSSSPPPQWWWWWWDDDDDDDDDDDPPHHHHHZZZZZZZZZZZZZZQQXLVVVVVVBBBBB",
        "ZZZZZZIIWWWWWWWWWNNNNNNNNSGGXTTTTTTTTTTTTTTTTTIIIBBBBXXXXFFFFFFFFFFFFKKKXJVJSSSSSSQPPPQQQQWWWDDDDDDDDDDDDDNHHHZZZZZZZZZZZZZZZXXXVVVVVVVVBBBB",
        "ZZZZZIIIIDWWWWWWWNNNNNNNNNNGGJJTTTTTTTTTKTTKKKIIIIIIBXXXFFFFFFFFFFFFKKJJJJJJJSSSSQQQQQQQQQIIIDDDDDDDDDDDDNNNNNZZZZZZZZZZZZZZZXXXVVVVVVVVVBBB",
        "ZZZZZZZIIIIIWWWNNNNNNNNNNNNRGGTTTPPPPPPKKKKKIIIIIIIIXXIXXXFFFFFTTFFFKJJJJJJJSSSSSSQQQQQQQIIIIDDDDDDDDDDDDDNNNNNZZZZZZZZZZZZLLXVVVVVVVVVVBBBB",
        "ZZZZZZZIIIIIWWEEEEEEEEEENNNNGGGTTPPPPPPKKKVKKKIIIIIIIIIIXXFFFFFFJJJJJJJJJJJJJSSSSSQQQQQQQIIIIDDWDDDDDWWDNNNNNNNZZZZZZZZZZZZLLXXXXVVVVVVBBBBB",
        "ZZZZIIIIIIIIIIEEEEEEEEEENNNNGGGVVPPPPPPKKKVVKKIIIIIIIIIIIIFFFFFFJJJJJJJJJJJJJJSSSQQQQQQQQIIIIIIIDDDDDGWNNNNNNNNNZZZZZZZZZZZLXXXXXVVVVVBBBBBB",
        "ZZZZIIIIIIIIIIEEEEEEEEEENNGGGGGGVPPPPPPVVKVVKVIIIIIIIIIIIIITFFFFIIIJJJJJJJJJJPPSSTQQQQQQQIJIIIJJDDDGGGNNNNNNNNNZZZZZZBZZZZZLXXBXXXXVVVVBBBBB",
        "ZZZZIIIIIIIINNEEEEEEEEEENGGGGGGVVPPPPPPVPPPPVVVIIIIIIETIITTTTFFFIIIIJIJJJJJJJPSSTTQQQQQQQZIIJJJJJJJGGANNNNNNNNNNZZZZZBYYYYBBBBBBXXBBBBBBBBBB",
        "ZZZZIIIIIIINNNEEEEEEEEEEGGGGGGVVVPPPPPPPPPPPVVVIIIIIRETITTTTTTFFIIIIIIIJJIJJJJIIIIQQQQQQQZZZZZJJHHGGGANNNNNANNNNZBZZZBBBBBBBBBBBXXBBBBBBBBBB",
        "ZZZIIIIIIIIEENEEEEEEEEEEGGGGGGGVVPPPPPPPPPPPPIIIIIIIIETTTTTTTTFIIIIIIIIIIIJJJJIIIQQQQQQZZZZZZHHHHHHFAAAAPANAANNNABZZZBBBBBBBBBBBBXXXBBBBBBBB",
        "ZZZIIIIIIEEEEEEEEEEEEEEENNGGGGHHVPPPPPPPPPPPBIIIIIIIIEEETTTTTTFIIIIIIIIIIIJIIIIIQQQQQQQZZZUZHHHHHHLHHAAAAAAAAANNABBBBBBBBBBBBBBBBXXXBBBBBBBB",
        "DZZIIIIIIEEEEEEEEEEEEEEERRDGGGVVVPPPPPPPPPPPPPPPPPPIEEEEETTTTFFFIIIIIIIIIIJIIIIIQQQQQQJJJZZZHHHHHHHHHHAAAAAAAHNNNBBBBBBBBBBBBBBXXXXXXBBBBBBB",
        "DIIIIIIIIEEEEEEEEEEEEEEERDDGGVVVVPPPPPPPPPPPPPPPPPPEEETTETTTFFFFIIIIIIIIIIIIIIIIIEQQQQIIIOYYHHHHHHHHHAAAAAAAAANNNBBMBBBBBBBBBBBBXXXXXBBDBBBB",
        "DIIIIIIDEEEEEEEEEEEEEEEERDDGVVVVVVVPPPPPPPPPPPPPPPPKEETTTTTTFFFFFFIIIIMMIIIIIIIIIIIQQQIIIYYYHHHHHHHHHAAAAAAAAAABNBBBBBBBBBBBBBBBXXXXXXDDDBBB",
        "DIIIIDDDEEEEEEEEEEERRRRRDDDDDDDVDDDPPPPPPPPPPPPPPPPRRRTTTTTTTFFFFFMMMMMMMMIIIIIIIIIIIIIIIIYYHHHHHHHHHAAAAAAAABBBBBBBBWBBBBBBBBBBXXXXXXUUDBBB",
        "DDIDDDDDEEEEEEEEEEERRRRRJDDDDDDDDHVPPPPPPPPPPPPPPPPRMTTBTTTFFFFFFFFFFMMMMMMIIIIIIIIIIIIINNYYHHHHHHHHAAAAAAAAAABBWBABWWBBBBBBBGGBUUXSUUUUUBBB",
        "DDDDDSSSSEEEEEEEEEERJJRJJJDDDDDDHHMPPPPPPPPPPPPPPPPRMTTTTTTFFFFFFFFFMMMMMMMMMMIIIIIIIINNNNYYNHHHHHHHHHAAAAAAQWWWWWAWWWBBBBBBBGGBUUXSUUUUUUUB",
        "DDDDDSSSSEEEEEEEEEERJJJJJDDDDDHHHHHPPPPPPPPPPPPPRRRRRRTTTTTFFFFFFFFFFMMMMMMMIIIIIIIIIINNNNNNNNHHHHHHHHAAAAAAWWWWWWWWWWWBBBBBBBBUUUXUUUUUUUUU",
        "DDDDSSSSSSSSSSSSRRRRRAAJJJDGDDHHHHHHHPPPPPPPPPPPRRRRRRTTTTTFFFFFFFFFFFMMMMIIIIIIIIIIINNNNNHHHHHHHHHHZHAAAAAAWWWWWWWWWWWWWWSSBBUUUUUUUUUUUUUU",
        "DDDDDSSSSSSSSSSSRRRHHHHJJDDGDHHHHHHHHPPPPPPPPPPPRRRRRRTTTTTFFFFFFFFFFFMMNIIIIIIIIIIIINNNNNNNHNHHHHHHZZZAIIIWWWWWWWWWWWWWWWSBBBAUUUUUUUUUUUUU",
        "DDDDDDDSSSSSRSSSSHHHHHHJDDDGDDHHHHHHHPPPPPPPPPPPRRRRURHTTTFFFFFFFFFFFFFNNIIIIIIIIISINNNNNNNNNNNHHHHHAZZZIIIWWWWWWWWWWWWWWWSSBAAUUUUUUUUUUUUU",
        "DYDDDDDSSSSSRSRRHHHHHHHHHDGGTTTTTTTTTTPPPPPPPPPPRRRRURHTTTTTUFFFFFFFFFNNNIIIIIIIIISSSNNNNNNNNNNHHHHHZZZZWWWWWWWWWWGWWXXWWXXSXXAUUTUUUUUUUUUU",
        "YYYDDDDSSSSRRRRRRHHHHHHHDDGGTTTTTTTTTTPPPPPPPPPPRRDDTTHTXTUUUFFFFFFNNFYNYIIITIISSSSSSSNQQQQQQAAAAAAHZZZZWWWWWWWWWGGWWXXXXXXXXXXTTTUTTUUUUUUU",
        "YYYYDEEEESRRRRRRRHHHHHHHHGGGTTTTTTTTTTPPPPPPPPPPRDDTTTTTTTUUFFFFFFFNNYYYYYYTTTSSSSSSSSNQQQQQQAAAAAAZZZZZZWWWWWWGGGGWWWWXXXXXOOOXTTTTJJJUUUUU",
        "YYYYYETYESEEEQQQQQQQQQQHGGGGTTTTTTTTTTPPPPPPPPPPRRRTTTTTTTUUFFFFFFNNNNYYYYYTTTTSSSSSSNNSSSQQQAAAAAAZZZZZZWIIIGGGGGGWKWXXXXXXOOOXXXXXJJJUUUUU",
        "YYYYYTTYEEEEEQQQQQQQQQQGGGGGTTTTTTTTTTPPPPPPPPPPRTRTTTTTTTUUUTFFNNNNYYYYYYYTYTSSSSSSSSSSSNSSSAAAAAAZZZZZZWIIGGGGGGGWWXXXXXXXOOOXXXJJJJJJJUUU",
        "YYYYYYYYYEEEEQQQQQQQQQQQGGGGTTTTTTTTTTPPPPPPPPPPTTTTTTTTTTTTTTTTTTNNYYYYYYYYYTSSSSSSSSSSSSSSSAAAAAAGGGZZZIIIGGGGGGGSWWWXXXXXOOOXXUJJJJJJJJUU",
        "YYYYYYYYEEEEEEEEHHHQQQQQGGGGTTTTTTTTTTTTTTTTPPPPTTTTTTTTTTTTTTTTTTYYYYYYYYYYYTSSSSSSSSSSSSSSSAAAAAAGGGRZZZIGGGGGGGGXXVXXXXXXOOOXXUJJJJJJJJJU",
        "YYYYYYYYYYEEEEEEEHHQQQQQGGGGTTTTTTTTTTTTTTTTPPPPWTTTTTTTTTTTTTTTTTYYYYYYYYYYYTTSSSSSSSSSSSSSSAAAAAAGRRRZZGGGGGGGGGGXXXXXXXXXOOOXXUUJUJJJJJJU",
        "YYYYYYYYKYEEEEEEEEEQQQQQGGGGTTTTTTTTTTTTTTTTPPPPTTTTTTTTTTSTTTTTTTYYYYYYYYYYSSSSSSSSSSSSSSSSSAAAAAARRRRZZGYGGGGGGGGGXXXXXXXXOOOMMUUUUJJJJJJU",
        "YYYYYYYYEEEEEEEEEEEQQQQQGGGGTTTTTTTTTTTTTTTTWWTTTTTTTTTPTTSTYTTTTTYYYYYYYYSSSSSSSSSSSSSSSSSSSSSSSMRRRRRRYYYGGGGGGGGAAAAXXXXXXXXMMJJJJJJJJJJG",
        "YYYYYYYYYEEEEEEEEEEQQQQQGGGGGGGGHWTTTTTTTTTTTTTTTTTTTPPPPPSSTTTTTTYYYYYYYYYSSSSSSSSSSSSSSSSSSSSSSSRRRRRRYYGGGGGGGGGPAAAAXXMMMMMMMGJJJJJJJJGG",
        "YYYYYYYYYYEEEEEEEEEQQQRRGGGGGGGGWWTTTTTTTTTTTTTTTTTTPPPPPPSPSSTTTTYYYYYYYYYSSSSSSSSSSSSSSSSSSSSSSRRRRRRGGGGGGGGGGGAAAAAAAAMMMMMMGGGGGJJJJJGG",
        "YYYYYYYYYYEEEEEEEEEQQQRRGGGGGWZWWWTTTTTTTTTTTTTTTTTTPPPPPPPPPPTTTTTYYJJYYYYYYYSSSUSSSSSSSSSSSSSSSRRRRRRGGRGGGGGGGFAAAAAAAAMMMMMMGGGGGGGJGGGG",
        "YYYYYYYYYYEEEEEEEEEQQQRRRGGZZWWWWWTTTTTTTTTTWWWTTTTTTTPPPPPPPPXTTTGJYJJYJJJJYYYSSUSSSUSSSSSSSSSSSRRRRRRRRRRRRLLLLAAAAAAAMMMMMMMMMGGGGGGGGGGG",
        "YYYYYYYYYMEEEEEEEEEQQQRRRGGHZZZHWWWWWWWWWWWWJJQTTTTTTTTPPPPPPPPGTTGJJJJJJJJJYYYYYUUUUUSSSSSSSSSSSRRRRRRRRRRLLLLLLAAAAAAAFMMMMMMMMMGGGGGGGGGG",
        "JYYYYYYNNMMMMEEEEEEQQQRHGGGHHZHHWWWWWWWWWWWWWJQTTTTQQTTPPPPPPPPGGGGJJJJYJJJJYYYYYUUUYYYUSSSSSSSSSRRRRRRRRRRLLLLLLAAAAAAAMMMMMMMMMMMGGGGGGGGG",
        "JJYYYMYNNMMMMEEEEEMQQQHHHIHHHHHHHHWWWWWWWWWWQQQTTQQQQTTPPPPPPPPGGGGJJJJJJJJJYJYYYUUUYYYUUSSSSSXXSRRRRRRRRRRLLLLLLALLAAAMMMMMMMMMUMMGGGGGKGKG",
        "JJYKYMMKKKMQQQQQQQQQQQHHHHHHHHHHHHHWWWWWWWWWQQQQQQQQQQPPPPPPPPPGJGJJJJJJJJJJJJYLYUUUYYYUUSUUSSSSWWSRRRRRRLLLLLLLLLLLMTMMMMMMMMMMMMMMMGGGKKKG",
        "JJJKKMMKKKKQQQQQQQQQQQHHHHHHHHHHHHHHHWWWWWWWQQQQQQQQQQPPPPPPPPPJJJJJJJJJJJJJJJLLUUUUYYYUUUUUSSSSSWSSRRRLLLLQLLLLLLLLMMMMMMMMMMMMMMMGMGGKKKKK",
        "VVKKKKMKKKKQQQQQQQQQQQHHHHHHHHHHHHHHHWWWWWWSQQQQQQQQQQPPPPPPPPPJJJJJJJJYYYYYYNNLUUUUYYYUUUUUSSSSSSSSSQQQQLQQQLLLLLLLLMMMOOMMMMMMXMGGGGGKKKMK",
        "VVKKKKKKKKKQQQQQQQQQHHHHHHHHHHHHHHHHHHHHWWWSSQQQQQQQQQPPPPPPPHPPHHJJJJJYYYYYYYYYYYYYYYYYYUUUSSSSSSSSTQQQQLQQLLLLLLLEMMMMOOMMMGMGGGGTTGGKKKKK",
        "VVKKKKKKKKKQQQQQQQQQHHHHHHHHHHHHHHHHHHHSSWSSSQQQQQQQQQPPPPPPPHHHHHJGGJJYYYYYYYYYYYYYYYYYYVVVVSSSSSSSQRQQQQQQQLLLLLEEEOOOOMMMMGGGGTTTTKKKKKKK",
        "VVKKKKKKKKKQQQQQQQQQHHHHHHHHHHHHHHHKKKKKSSSSSQQQQQQQPPPPPPPPHHHHYYYYYYYYYYYYYYYYYYYYYYYYYVVVVSSSSQQQQQQQQQQQQLLLLNEEEEEOMMMGMGGGGGTTTKKKKKKK",
        "VKKKKKKKKKKQQQQQQQQQHUUUUHHHHHHHHUHKKKKKSSSSSSSQQQQQQSSPPPPPHHHHYYYYYYYYYYYYYYYYYYYYYYYYYVVVYVSSSSQQQQQQQQQQQLLNNNNEEEEEEMGGGGGGGGGTTTKKKKKK",
        "VKKKKKKKKKKQQQQQQQQQUUUUUHHHHHZHHUHKKKKKSSSSSSSQSQQSSSSSPQPHHHHGYYYYYYYYYYYYYLLLLLLYYYYYYVVVVVSSSSQQQQQQQQQQQQLNNNNEJJGGGGGGGGGGGGGTTTTTKKKK",
        "VKKKKKKKKKKQQQQQQQQQUUUUUUUUHHKKKKKKKKKKSSSSSSSSSSQSSSSSPPPPGGGGYYYYYYYYYYLLLLLLLLLYYYYYYVVVSSSSSSQQQQQQQQQLLLLNNNNNJJJJGGGGGGGGGGGTTTTTKKKE",
        "VKKKKKKKKKKSSMMBMMUUUUUUCUUUHKKKKKKKKKKKKSSSSSSSSSSSSSSSSSPSSGGGYYYYYYYYYYLLLLLLIILYYYYVVVVVVSSSSSSSQQQQQQQQRRLNJNJJJJJGGGGGGGGGGGGTTTTTKEEE",
        "VVKKKKKKKKKIIBBBBMEUUUUUCUUHHKKKKKKKWKKKSSSSSSSSLLLSLSSSSSPGGGGGGGGGGGQQQQLLLLLLLLLLLVVVVVVVVSVSSSSSSSQQLQRRRRRJJJJJJJJGGKGGGGGGGGUTTTTTKEEE",
        "VVKKKKKKKKKIIBBBEMEEUUUCCCCCCCKHKKKKWWWWUUSUSSSLLLLLLSSSSSSGZGGGGGGGGGQQQQQQULLLLVVVVVVVVVVVVVVSSSSSSSQQQQRRRJRJJJJJJJDLGGGGGGEGGGUUTTTTTEWE",
        "VVKKKKJKIKIIIBBEEEEEUUUUUUCCCCCCKKKKWWWUUUUULSSLLLLLSSSSSSSZZZGGGGGGGGQQQQQQLLLLLLVVVVVVVVVVVVSSSFSSSSSSRRRRRJJJJJJJJJDLLLLLDEEEDUUUUUUUUWWE",
        "VVVKKKJKIKIIEEEEEEEEEUUUUUCCCCCCCKKKWKWWUUUULSSLLLLSSSSSSSSSSZGGGGGSGQQQQQQLLLLXXVVVVVVVVVVVVVAAFFSFFSSSRRRRRRJJJJJJJJDLLLDDDEDDDDUUUUWUUWWW",
        "VVVKKIKKIIIIIEEEEEEEEUUUUUCCCCCCCCPKKKWUUUUULLLLLLSSSSSSSSSSSZGGGGSSSQQQQQQQLLLLRRVVVVVVVVVVAVAAFFFFFFFSRBBBRRJJJJJDDDDDDDDDDDDDDDUUUWWWWWWW",
        "VVVKIIIIIIIIIEEEEEEEEUUUXCCCCCCCCCCKKKUUUUUUULXLLLQQQSQQQSSSQGGGGSSQQQQQQQQQHLRRRVVVSVVVVVVVAAAAFFFFFFBSNBOBOBBJJJBBDDDDDDDDDDDDDUUUUWWWWWWW",
        "IIIIIIIIIIIIIIIEEEEEEUUXXEXCCCCCCCCYKUUUUUUUUXXLLLQQQQQQQQQQQGGGSSSSQQQQYYQQQRRRRRVVVVVVVVVVAAAAFBBFFFBBBBBBBBBBBBBBDDDDDDDDDDDDDUUUUWUWWWWW",
        "IIIIIIIIIIIIIIIEEEEEEUXXXXXCCCCCCCCYUUUYUYUUUXXXRVQQQQQQQQQQQGQQQSSSSQQQRQQQRRRRREVVPVVVVVVVVAAYJYFFFYBBBBBBBBBBBBBBSDDDDDDDDDDDDUUUUUUWWWWW",
        "IIIIIIIPIIIIEEEEEEEEEXXXXXXZZZCCCCCYYYUYYYYUUXRRRRQQQQQQQQQQQQQSSSSSSSSRRRRRRRRREEVEEYVVVVVVAAAYYYYYYYBBBBBBBBBBBBBBBDDDDDDDDDDDDUUUUUUWWWWJ",
        "IIIIIIIIIICCEEWEEEBXXXXXXXXZZZZCCCZYYYYYYYYYYRRRRRRRQQQQQQQQQQQQSSSSSSSRRRRRRRRRREEEEYYAVVVVAAAAAYYYYYYBBBBBBBBBBBBBDDDDDDDDDDDDDUUUUUUWWWWJ",
        "IIIIIIIIIIIIIEWWEEEEXXXXXXXZZZZZZZZZZZYYYYYYYRRRRRRRQQQQQQQQQQQSSSYSSSRRRRRRRRRREEEJEEEAAAAAAAAAAYYYYYBBBBBBBBBBBBBBDDDDDDDDDDDDUUUUUUUUWWJJ",
        "IIIIIIIIJIIIIWWWCCEEMMXXXXXZZZZZZZZZZYYYYYYYYRRRRRRRRQQQQQQQQQQQSSYSSSRRRRRRRRRRRREJJEAAAJJJJAAAYYYYYYYBBBBBBBBBBVVVEEDDDDDDDDDDUUUUUUUUWJJJ",
        "IIICIIIIIIIIIIIWWCEEMMXXXXXXZZZZZZZZZHHHYYUUYRRRRRRRRRQQQQQQQQQYYYYYYRRRRRRRRRRRRRJJJJJJAJJJAAAAAAYYYYYYYBBBBBBBBBVVVVDDHHDDDDDDUUUUUUUUUUJJ",
        "IIIIIIIIIIIIIIIWWCCCMMMXXXXZZZXZZZFZVVHHYYUUURRRRRRRRRRQQQQQQQQQYYYYYRRRRRRRRRRRRRRJJJJJJJJJAAAAAYYYYYYYYPBIBBBBBBDVVHHHHHDDDDDUUUUUUUUUUUJJ",
        "IIIIIIIIIIIIIIIWCCCMMMXXXXXXXXXXZZHHHHHHYUUUURRRRRRRRRRRQQQQQQSYYYYYYRJRRRRRRRRRRRJJJJJJJJJXXAAAYYYYYYYPPPBBBBBBBVVVVVHHHHHDDDDUUHHHUUUUUJJJ",
        "IIIIIIIIWIIIIYYYYYCYXXXXXXXXXXXXZZXXHHHHUZUURRRRRRRRRRRRQQIQQYYYYYYYYYJJRRRRRRRRRJJJJJJJXJJXAAAPPPPPPPYPPPPPBBBBVVVVVVVVHHHHHDHHHHHUUUUUGGGG",
        "IIIIIIIIIIIIIYYYYYYYXYXXXXXXXXXXXXXXXXHHUUUUURRRRRRRRRRLQQIYQYYYYYYYYJJJRRRRRRRRRRRJJJJXXXXXAAPPPPPPPPPPPPPPPBBBVVVVVVVVHHHHHHHHHHHUGGUGGGGG",
        "IIIIIIIIIIIIIYYYYYYYYYXXXXXNXXXXXXXXXJHHUUUUUUUUURRZRRRRQQYYYYYYYYYYYJJYYRBBBAARBRRJXXXXXXXXXXXXPPPPPPPPPPPPPPPPVVVVVVVHHHHHHHHHHHHULGGGGGGG",
        "IIIIIIIIIIIIIYYYYYYYYYYYYXXNXXXXXXXXXXHHHHUKUUUUURRZZRZRKQYYYYYYYYYYYYYYBBBABABRBRRBXBBXXXXXXXXXPPPPPLLPPLPLLPPPPVVVVVVHHHHHHHHHHHHUGGGGGGGG",
        "IIIIIIIIIIIIIYYYYYYYYYFFFNNNNNXXXXXXXXHHHHUUUUUUUZZZZZZYYYYYYYYYYYYYYYYYBBAAAABBBEBBBBXXXXXXXXXXXXPLLLLLLLLLLPPPPPPHVVHHHHHHHHHHHHHUUGGGGGGG",
        "IIIIIIIIIYYYYYYYYYYYYYFFFNNNCNXXXXXHHXHHHHHUUUUUUZZZZZZZZYYYYYYYYYYYYYYYBBAAAAPBBEBBBBXXXXXXXXXXXXPPLLLLLLLLLPPPPPPHHHHHHHHHHHHHHXUUGGGGGGGG",
        "IIIIIIIIIYYYYYYYYYYYYFFFFNNNNJJJJXXHHHHHHHHHZZUUZZZZZZZZZZYGYYYYYYYYYYYYAAAAABBEBBVVVVVVVVXXXXXXXXXXLLLLLLLLLLPPPPPPHHHHHHHHHHHHHHOOGGGGGGGG",
        "IIIIIIIIIWYYYYYYYYYYYFFNNNNNNJJJJXXXSHHJJJXJJZZZZZZZZOOZZZYGYYYYYYYYYAYAAAAAABBBBBVVVVVVVVXXXXXXXXXXLLLLLLLLLLPPPPPPPPPPPPPPPHHHHHOOGGGGGGGG",
        "GGGWWWWWWWYYYYYYYYYYYYFFFNNNNJJJJSSASSHJJJJJJJJZZZOOOOOZZZYYYYWYYYYYYAAAAAAAAABBBBVVVVVVVVXXXXXXXXXXLLLLLLLLPPPPPPPPPPPPPPPPPHHHHOOOOGGGGGGG",
        "GGGGWWWWWWYYYYYYYYYYYMXFFFNNNJJJSSSSSWJJJJJJJJZZOOOOONNOOOOOBYWWWWWAAAAAAAAAAAABBBVVVVVVVVXXXXXXXXLLLLLLLLLLLPPPPPPPPPPPPPPPPOHHHOOOOOGGGGGG",
        "GGGWWWWWWWYWNYFYYYYYYMXFFNNNNNSSSSSJJJJJJJJJJJOOOOOOOOOOOOOZOYWWWWAAAAAAAAAAAAABBBVVVVVVVVXXXXXXXXLLLLLLLLLLLLLPPPPXPXXPPPPPPPHHHHHHHOGGGGGG",
        "GGGGGWWWWWWWWWFFFYFXFFXXXXXXTNZSSSSJJJJJJJJJNGGGOOOOOOOOOOOOOWWWWWAFFAAAAAAAAAAABBVVVVVVVVXMXXXXXXTTTLLLLLLLLLLPPXPXXXXPPPPPPPHHHHHHHGGGGGGG",
        "GGGMGGWWWWWWWWFFFFFFFFXXXXXXXSSJSSSJJJJJJJJGGGGGOOOOOOOOOOOOOOWWWAFFFAAAAAAAAAAIIHVVVVVVVVVVVVVXXXTTTLLLLLLLLLLLLXXXXXXTXPPPPPPPHHHHHZGGGGGG",
        "GGGGGGWWWWWKKKFFFFFFMMMMMMMMMSSSSSSJJJJJJJJJGCGGGGOGGOOOOOOOOBIWWAAFFAAAAAAAAAAAHHVVVVVVVVVVVVVGXXTTTTELLLLLLGLGLXXXXXXXXPPPPPPPHHHHHZZZGGGG",
        "GGGGRRWWWWWWWFFFFFFFMMMMMMMMMSSSSJJJJJJJJJJJPJGGGGGGGGOOOOOBBBIIAAAANNNNNNNNNNAAHHVVVVVVVVVVVVVGXXTTTTLLLLLLLGLGGXXXXXXXXPPPPPPPHHHHHZZZGGGG",
        "GGRRRRRRRRRRRRFFFFFFMMMMMMMMMSSSSSJJJJJJJJJJPJGGGGGGGGGGGOOBBIIIAAAANNNNNNNNNNAEHXXXHHHOVVVVVVVGGGGTTOLLLLLLLGGGGXXXXXXXXPPPPPPPHHHHHZZZGGGG",
        "RRRRRRRRRRRMMMMMMMMMMMMMMMMMMSSSSSSJJJJJJJJJJJJGGGGGGEGEOOBBBBIIIAAANNNNNNNNNNEEXXXXXHHHVVVVVVVGGGTTTTIILLLLLGGGXXXXXXXXXPPPPPPPHHHHHZZZGGGZ",
        "RVRRRRRRRRRMMMMMMMMMMMMMMMMMMSSSSJJJJJJJJJJJJJJGGGEGGEEEEEBBBBIIINNNNNNNNNNNNNXXXXXXXUHHVVVVVVVWGGGTTTIILLFLGGGGXXXXXXXXXPPPHHHHHHHHHZZZGGGZ",
        "VVVVRRRRKKKMMMMMMMMMMMMMMMMMMZZSSJJJJJJJJJJWJJGGGGEGGEUUUUBBBBBBINNNNNNNNNNNNNXXXXXXXXHHVVVVVVVWGGGGGYIILLLGGAGGGXXXXXXXXPPPHHHHHHHHHDZZZZZZ",
        "VVVRRKKKKKKMMMMMMMMMMMMMMMMMMZZZZJJJJJJJQJXJJXXEEGEEEEUUUUEEIIIIINNNNNNNNNNNNNXXXXXXXXXHVVVVVVVVVGGGGYIILGGGGAGGGGGXXXXPPPHHHHHHHHHHHDDDZZZZ",
        "VVVRKKKKKKKMMMMMMMMMMMMMFFPZZZZZJJJJJJJJJJXXXXEEEEEEEEUUUUEEIIIIINNNNNNNNNNNNNXXXXXXXXXHVVVVVVVVVGGGGYIAAAGGAAGGGGGGXXXPPPHHHHHHHHHHHDDDDDZZ",
        "VVVRKKKKKKKMMMMMMMMMMMMMFPPZZZZZZZZZJJYYYJXXAEEEEEEEEEUUUUEMEIINNNNNNNNNNNNNNNXXXXXXXXWWWWWVVVVVVWWGGYYAAAAAAAAAAGGGGGGPPPHHHHHHHHHHHDDYDDZZ",
        "VVVVVVKKKKWMMMMMMMMMMMMMPPPPPSZZZZZZZJYYYYAAAEEEEEEEEEUUUUEEEIINNNNNNNNNNNNNNNXXXXXXXWWWWVVVVVVVVWGGGGGAAAAAAAAAAGGGGGGGPPHHHHHHHHHHHDDDDDDZ",
        "VVVVVVJJVKKKWWWIIIHHHHHHHPPPPSSSZZZZZZPPYYAAAAAEUUUUUUUUUUEIIIINNNNNNNNNNNNNNNXXXXXXXJJJWVVVVVVVVWGGGGGGAAAAAAAAAAAGGGGPPPHHHHHHHHHDDDDDDXDZ",
        "PVVSVVVVVKWWWWWIHHHHHHHHHHPPPSSSSZZPPPPPAYAAAAWAUUUUUUUUUUYYIIINNNNNNNNNNIXXXXXXXXXXXJJJJVVVVVVVVWWWWGGAAAAAAAAAAAAAGRRPRFHHHHHHHHHDDDDDDDDD",
        "PVSSVVVVVVWWWWIIHHHHHHHHHLLPSSSSSZZPPPPPAAAAAAAAUUUUUUUUUEYYIIINNNNNNNNNNIXXXXXXXXXXJJJJJVVVVVVVVWWWWGGGAAAAAAAAAAARRRRRRRHHHHHHHHHDDDDDDDDQ",
        "VVVVVVVVHVWWWIIIIIHHHHLHLLLLLLSSZZPPPPPPAAUUUUUUUUUUUUUUUEYIIIIIIIIINNNNNXXXXXXXXXXXJJJJJVVVVVVVVWWWGGGGGGAAAAAROOORRRRRRRZZZZHHHHDDDDDDDDDD",
        "VVVVVVVIIIIIIIIIIHHHIKLLLLNLLLSSZZPPPPPPAAUUUUUUUUUUUUUUEEYYIIIIIIIINNNNNGGGXXXXXXXXJJJJJVVVVVVVVWWWWWGAAAAAAAARRORRRRRRRRZZZZHHHHZDDDDDDDDJ",
        "QQVVVVVVVBIIIIIIIIIIIKLLLLLLLLLLLPPPPPPPAAUUUUUUUUUUUUUUEYYIIIIIIIIGNNNNNGXXXXXXXXXXXXXJZXWWWWWWWWWWWGGGAAAAAAARRRRRRRRRRRZZZZHHHHDDDDDDDDJJ",
        "QVVVVVVVIIIIIIIIIIIIIIILLLLLLLLLLLPPPPPPPAUUUUUUUUUEEEXEEEYIIIIIIIIKNNNNNGXXXXXXXXXXXXXXXXWWWWWWWWWWWQGGGAAAAAAARRRRRRRRRZZZZZHHHHDDDDDDDDDJ",
        "QVVVVVVVIIIIIIIIIIIIIIILLLLLLLLLLLPPPSPPPAUUUUUUUUUEEEEEEEYQAIIRIIIKGGGGGGXXXXXXXXXXXXXXXXXWWWWWQWWQQQGGGGGAAAAARRRRRRRRRRZZZZZZZZZDDDDDDKDJ",
        "VVVVVVVVVIIIIIIIIIIIIIIQLLLLLLLLLLLLLLPJJJUUUUUUUUUJJJQQEEYQQQRRRRGGGGGGGGXXXXXXXXXXXXXXXXXWXWWWQWQQQQGGGGGGGAARRRRRRRRRRRRZZZZZZZZDDDDDDDHH",
        "VVVVVVIIIIIIIIIIIIIIIQQQLQLLLLLLLLLLJJJJJJUUUUUUUUUJQQQQQQQYYQRRRRRRGGGGGGXXXXXXXXXXXXXXXXXXXXXXQQQQQQGGGGGGIHRRRRRRRRRRRRRRZYYZZZZZDYHHHHHH",
        "VVVVVVIUUUIIIIIIIIIIIQQQQQLLLLLLLLLLLJJJJJUUUUUUUUUJQQQQQQQQYQQRRJRGGGGGXXXXXXXXXXXXXXXXXXXXXXXGGEQQQQGGGIIIIIJRRRRRRRRRRRRRYYYYZYYZYYYHHHHH",
        "VVVVVVVUUVIIIIIIIIQQQQQQQQLLLLLVLLLLLJJJJJUUUUUUUUUJJQQQQQQQQQRRJXXXXXXXXXXXXXXXXXXXXZZZZXXXXXXGEEQQEGGGGIIIIIIPPRRRRRRRRRRRYYYYYYYYQYYHHHHH",
        "VVVVVVVVVVVZIIIIIQQQQQQQQQLLLVLVJJLJJJJJJJUUUUUUUUUJJQQQQQQQQQRJJXXXXXXXXXXXXXXXXXXXXZZZGXHHEEEEEEEQEGGGIIIIIIPPPRORRRRRRRRRKYYYYYYYYYYYHHHH",
        "QVVVVVVVVVZIIIIIIQQQQQQQQQQQLVLVVJJJJJJJJJJJJJJJJQQQQQQQQQQQQQQJJXXXXXXXXXXXXXXXXXXXXZZZZVHHHEEEEEEEEGGGIIIIIIIIIOORURRRKRRKKYYYYYYYYYYYHHHH",
        "QQVVVVVVVPIIFFIIIIQQQQQQQQQQQVVVVVVVVJJJJJJJJJJJJQQQQQQQQQQQQQQJJJJJJJJKXXXXXXXXXXZZZLLLZVHHEEEEEEEEEGGGIIIIIIIIIIOOINNRKKRKKYYYYYYYVVYHHHHH",
        "QQQQVVVVVVIIIIIIQQQQQQQQQQQQVVVVVVVJJJJJJJJJJJJJJQQQQQXXQQQQQQGOJJJJJJJMXXXXXXXXXXZLLLLLVVVHEEEEEEEEEEEEEIIIIIIIOOOOIINRKKKKKYYYYYYYYVYHHHHH",
        "QQQVVVQQQQIIMIIQQQQQQQQQQQKQQVVVVVVJJJJJJJJJJJJJJQQQQQXXXXQQQQOOJJJJJJWMXXXXXXXXXXZCLLLLVVVEEEEEEEEEEEEEEEIIIIIIIIIIIIRRKKKKKYYZYYYYYYHHHHHH",
        "QQQQQQQQQQQMMLQQQQQHHQQQQKKQQQVVNNKKJKKJJJJJJJJJJIQQQQQXXXXOZQOOJJJJJJWWXXXXXXXXXXZLLLLVVVEEEEEEEEEEEEEEEEIIIIIIIIIIIIIIIIIKKYYZZCYYYYYHHHHH",
        "QQQQQQQQQQQQMLQQQQQHHHQQQQKQQQQQQNKKKKKKQQQIEJJJJIQQQIIIIIXOQQOOJJJJJWWWXXXXXXXXXXZLLLAAAVEEEEEEEEEEEEEEVVXIVVVIVIIIIIIIIIIIIYZZZCYYYYYHHHHH",
        "QQQQQQQQQQQQLLLLLQQQQHHHHHKKYQYFYNKKKKKKQIIIJJIJIIIIIIIIIIOOOOOOOJJWWWWZXXXXXXXXXXVVVLAAAAAEEEEEEEEEEEEEVVVVVVVVVIIIIIIIIIIIZZZZCCHHHHHHHHHH",
        "QQQQQQQQQLLLLLLLQQQQQHHHHKKKYYYYYYBKKKKKIIIIIJIIIIIIIIIBOOOOOOOOOOAAWWWWWZZOVVVVVVVVVVVAAAAAAAEEEEEEEEEEVVVVVVVVVIIIIIIIIIIIIIZCCCCHHHHHHHHH",
        "QQQQQQQQLLLLLLLQQQQQHHHHHKKKKCYYYYGGGKKKIIIIIIIIIIIKKIIBBOOOOOOOOAAAWWWWWZZOOOOVOOVVAAVAAAAAAAEEEEEEEEEVVVVVVVVVIIIIIIIIIIIIIZZCCCCCHHHHHHHH",
        "QQQQQQQLLLLLLLLLLQQQQHHHKKKKKYYYYYGGKKIIIIIIIIIIIIIKKHRRRREOOOOOOAAAAAWWWWWOOOOVOOOAAAAAAAAAAAEEEEEEEEVVVVVVVKKIIIIIIIIIIIIZIZZCCCCCKKHHHHHH",
        "QQQQQQQLLLLLLLLLLLLLLHHHHHKKKKYKKKKGKKIIIIIIIIIIIIIKKRRRRRROOOOOOAAAAWWWCOSOOOOOOOOAAAAAAAAAAEEEEEEEEEVVVVVVVKDDKFIIIIIIIIZZZZZGCCCCKKHHKHHH",
        "QQQQQQLLLLLLLLLLLLLWBHHHHZZKKKKKKKKKKKKIIIIIIIIIIIIKKRRRRRRROOOOAAAAQCCCCOOOOOOOOOOAAAAAAAAAAEEEEEPPEVVVVVVVVVDDKFFFIIIIIIZZZZZGGGCCKKKKKKHH",
        "QQQQQQLLLLLLLLLLLLLWBWHHHHHKKKKKKKKKKKKIIIIIIIIIIIIKKRRRRRRRRLRAAAAAQQQQOOOOOOOOOOOAAAAAAAAAAAAEEPPPPVVVVVVVVADDFFFFIFIIZZZZZZGGGCCKKKKKKKKK",
        "QQQQQQLLLLLLLLLLLLLWWWHHKKKKKKKKKKKKKKKIIIIIIGIIIIIIIIRBRSRRRLRRAQQQQQQQOOOOOOOOOOOAAAAAAAAAAAAAEEPPPPVVVVVVVADDDFFFFFIIIZZZZGGGGCCKKKKKKKKK",
        "QNNNQQLLLLLLLLLLLLLWWWWWKKKKKKKKKKKKKKKIIIIIIGIIGIGIIIRRRRRRRRRRRRRQQQQQQQOOOOOOQOAAAAAAAAAAAGGGEEPPPPVQVQVVQDDDDFFFIIIIZZZZZZZGGGCCKKKKKKKK",
        "QQNNQHUOOLLLLLLWWWWWWWWWKKKKKKKKKKKKKKKKGGGGGGGGGKGIIRRRRRRRRRRRRRRRQQQQQQQQOOOQQAAAAAAAAAAAAAAGEEPPPPQQQQQQQDDDDDDDIIIIIIPZZZZZGMMCCCKKKKKK",
        "NNNNNUUUOLLLLLLWWWWWWWWKKKKKKKKKKKKKKKKKGGGGGGGGGKGIRRRRRRRRRRRRRXXQQQQQQQQQQQQQQQQAAAAAAAAAAAAGEDPPPPPPQQQQQDDDDDDDIIIIIIZZZZZZGZMMCCKKKKKK",
        "NNNXNUUUUULLXLLLWWWWWWKKKKKTKKKKKKKKKKKKGGGGGGGGGGGRRRRRRRRRRRRRRXXQQQQQQQQQQQQQQQQAAAAAAAAAAGGGGPPPPPPQQEQQQDDDDDDDIIIIIZZZZZZZZZMMCCCKKKKK",
        "NNNXUUUUUXLXWWWWWWWWWWTTTTTTKKKKKKKKMGHKGGGGGGGGGGRRRRRRRRRRRRRRRRQQQQQQQUQQQQQQQQQQAAAIIAAAGGGGGGGGPPEEEEDQDDDDDDDDDIIIZZZZZZZZZMMCCCMPKKKK",
        "NNXXUUUUUXXXXWWWWWWWWWWWTTTTKKKKKKKKMGGGGGGGGGGGGGGRRRRRRRRRRRMMRMMMQQUUQUUQQQQQQQQQQAAQQGAGGGGGGGGGPEEEEEDDDDDDDDDDDIIIZZZZZZZZZMMMMCMPMMKK",
        "XXXXXXXXXXXXXXXWWWWWWWWTTTTTTKKKKKTTGGGGGGGGGGGGGGGGRRRRRRRRRMMMMMMMMMUUUUUUUQQQQQQQQAAQQGGGGGGGGGGGPEEEEDDDDDDDDDDDKMMIZZZZZZZZZZMMMMMMMMKK",
        "XXXXXXXXXXXXXXWWWWWWWWWTTTTTTTTTKTTTGTTGGGGGGGGGGGGGGRRZRRRRRRRMMMMMMMUUUQQQQQQQQQQQQQAQQQGGGGGGGGGGEEEEEEDDDDDDDDDDKMIIZJZZZZZZZZMMZZTMKKKK",
        "XXXXXLXXXXXXXXXWWWWWWCTTTTTTTTTTTTTTTTGGGGGGGGGGGGGGGZZZZRVVRRRRMMMMMMUUUUQQQQQQQQQQQQQQGGGGGGGGGGGGEEEEEEYDDDDDDDDDDMMMZJJZZZZZZZZZZZTTKKKK",
    ]
    
    func neighbours(for pos: (Int, Int)) -> [(Int, Int)] {
        return [
            (pos.0 - 1, pos.1),
            (pos.0 + 1, pos.1),
            (pos.0, pos.1 - 1),
            (pos.0, pos.1 + 1),
        ]
    }
    
    func isInside(N: Int, M: Int, pos: (Int, Int)) -> Bool {
        return pos.0 >= 0 && pos.0 < N && pos.1 >= 0 && pos.1 < M
    }
    
    func flood(input: [String], for char: Character, from: (r: Int, c: Int)) -> [(Int, Int)] {
        let N = input.count
        let M = input[0].count

        var visited = [[Bool]](repeating: [Bool](repeating: false, count: M), count: N)
        var result = [(Int, Int)]()
        
        var queue = [(Int, Int)]()
        queue.append(from)
        
        while !queue.isEmpty {
            let currentPos = queue.removeFirst()
            visited[currentPos.0][currentPos.1] = true

            result.append(currentPos)

            let neigh: [(Int, Int)] = neighbours(for: currentPos).filter {
                isInside(N: N, M: M, pos: $0)
            }
            
            for n in neigh {
                let line = input[n.0]
                let nCh = line[ line.index(line.startIndex, offsetBy: n.1) ]
                if !visited[n.0][n.1] && nCh == char {
                    visited[n.0][n.1] = true
                    queue.append(n)
                }
            }
        }
        
        return result
    }
    
    func dowork() {
        let input = input3
        
        let N = input.count
        let M = input[0].count

        var visited: [[Bool]] = [[Bool]](repeating: [Bool](repeating: false, count: M), count: N)

        var result = 0
        
        for (i, line) in input.enumerated() {
            for (j, ch) in line.enumerated() {
                if visited[i][j] { continue }
                
                let currentBlob = flood(input: input, for: ch, from: (r: i, c: j))
                
                let area = currentBlob.count
                var perimeter = 0
                
                for (r, c) in currentBlob {
                    // print("\(ch): (\(r), \(c))")

                    let neigh = neighbours(for: (r, c))
                    for (nr, nc) in neigh {
                        if !isInside(N: N, M: M, pos: (nr, nc)) {
                            perimeter += 1
                            continue
                        }
                        
                        let nLine = input[nr]
                        if nLine[ nLine.index(nLine.startIndex, offsetBy: nc) ] != ch {
                            perimeter += 1
                        }
                    }
                    
                    
                    visited[r][c] = true
                }
                
                result += (area * perimeter)
            }
        }
        
        print(result)
    }
}
